all:
	gcc main.c aresta.c heap.c vector.c vertice.c -o trab1

run_muito_pequeno_1:
	./trab1 ../casos_teste_v3/caso_teste_muito_pequeno_1.txt ../casos_teste_v3/saida.txt

run_pequeno_1:
	./trab1 ../casos_teste_v3/caso_teste_pequeno_1.txt ../casos_teste_v3/saida.txt