all:
	gcc main.c aresta.c dijkstra.c heap.c vector.c vertice.c -o trab1

run_muito_pequeno_1:
	./trab1 ../casos_teste_v3/caso_teste_muito_pequeno_1.txt ../casos_teste_v3/saida.txt

valgrind_muito_pequeno_1:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_muito_pequeno_1.txt ../casos_teste_v3/saida.txt

run_muito_pequeno_2:
	./trab1 ../casos_teste_v3/caso_teste_muito_pequeno_2.txt ../casos_teste_v3/saida.txt

valgrind_muito_pequeno_2:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_muito_pequeno_2.txt ../casos_teste_v3/saida.txt

run_pequeno_1:
	./trab1 ../casos_teste_v3/caso_teste_pequeno_1.txt ../casos_teste_v3/saida.txt

valgrind_pequeno_1:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_pequeno_1.txt ../casos_teste_v3/saida.txt

run_pequeno_2:
	./trab1 ../casos_teste_v3/caso_teste_pequeno_2.txt ../casos_teste_v3/saida.txt

valgrind_pequeno_2:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_pequeno_2.txt ../casos_teste_v3/saida.txt

run_pequeno_3:
	./trab1 ../casos_teste_v3/caso_teste_pequeno_3.txt ../casos_teste_v3/saida.txt

valgrind_pequeno_3:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_pequeno_3.txt ../casos_teste_v3/saida.txt

run_pequeno_4:
	./trab1 ../casos_teste_v3/caso_teste_pequeno_4.txt ../casos_teste_v3/saida.txt

valgrind_pequeno_4:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_pequeno_4.txt ../casos_teste_v3/saida.txt

run_medio_1:
	./trab1 ../casos_teste_v3/caso_teste_medio_1.txt ../casos_teste_v3/saida.txt

valgrind_medio_1:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_medio_1.txt ../casos_teste_v3/saida.txt

run_medio_2:
	./trab1 ../casos_teste_v3/caso_teste_medio_2.txt ../casos_teste_v3/saida.txt

valgrind_medio_2:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_medio_2.txt ../casos_teste_v3/saida.txt

run_medio_3:
	./trab1 ../casos_teste_v3/caso_teste_medio_3.txt ../casos_teste_v3/saida.txt

valgrind_medio_3:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_medio_3.txt ../casos_teste_v3/saida.txt

run_medio_4:
	./trab1 ../casos_teste_v3/caso_teste_medio_4.txt ../casos_teste_v3/saida.txt

valgrind_medio_4:
	valgrind --leak-check=full ./trab1 ../casos_teste_v3/caso_teste_medio_4.txt ../casos_teste_v3/saida.txt