all:
	gcc main.c conexao.c heap.c vector.c dijkstra.c -o trab1

run_example:
	./trab1 ../casos_teste_v3/caso_teste_medio_4.txt ../casos_teste_v3/saida.txt

bt_test:
	gcc bt_test.c conexao.c heap.c vector.c dijkstra.c -o bt_test